version: '3.8'
services:
    app:
        container_name: news-portal
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        expose:
            - "9000"
    web:
        image: nginx:alpine
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8001:80"
        depends_on:
            - app
